import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
			</Head>

			<>
				<p>Home works!</p>
			</>
		</>
	);
};

export default Home;
